---
version: "3"
services:
  folding-at-home:
    build:
      context: .
    image: floodio/boinc
    container_name: boinc
    environment:
      - PROJECT_URL=${BOINC_PROJECT_URL}
      - ACCOUNT_KEY=${BOINC_ACCOUNT_KEY}
    restart: unless-stopped
